theme: jekyll-theme-minimal
title: Mucahit Cevik
description: Associate Professor of Industrial Engineering at Toronto Metropolitan University
logo: https://github.com/mucahitcevik2/mucahitcevik2.github.io/blob/main/mucahit_new.jpg alt="drawing" width="240"
show_downloads: false
