theme: jekyll-theme-minima
title: Mucahit Cevik
description: Associate Professor of Industrial Engineering at Toronto Metropolitan University
logo: https://i.postimg.cc/GmPcR3TG/mucahit-new.jpg
show_downloads: false
