theme: jekyll-theme-architect
title: Mucahit Cevik
description: Associate Professor of Industrial Engineering at Toronto Metropolitan University
logo: https://i.postimg.cc/GmPcR3TG/mucahit-new.jpg alt="drawing" width="180"
show_downloads: false
