theme: jekyll-theme-minimal
title: Mucahit Cevik
description: Associate Professor of Industrial Engineering at Toronto Metropolitan University
logo: assets/img/mucahit_new.jpg alt="drawing" width="240"
show_downloads: false
